[package]
authors = ["Mike Engel <mike@mike-engel.com>"]
edition = "2018"
name = "index"
version = "2.0.0"

[dependencies]
chrono = "0.4"
http = "0.1"
now_lambda = "*"

[[bin]]
name = "test"
path = "/Users/aw/code/github/vercel-runtime/api/rust/test.rs"
